{% set name = "radioactivedecay" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/radioactivedecay-{{ version }}.tar.gz
  sha256: 799bc806065b0b650ca4a0a9c416e3fdc1576fb9ac537a7965eeadd3c1f35f05

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - networkx
    - numpy
    - pandas
    - python >={{ python_min }}
    - scipy
    - setuptools
    - sympy

test:
  imports:
    - radioactivedecay
  commands:
    - pip check
    - python -m unittest discover
  requires:
    - pip
    - python {{ python_min }}
  source_files:
    - tests/

about:
  home: https://github.com/radioactivedecay/radioactivedecay
  license: MIT AND LicenseRef-AMDC AND LicenseRef-ICRP-07
  license_file:
    - LICENSE
    - LICENSE.AMDC
    - LICENSE.ICRP-07
  summary: Radioactive decay calculations in Python
  description: |
    A Python package for radioactive decay modelling that supports 1252
    radionuclides, decay chains, branching, and metastable states.
  doc_url: https://radioactivedecay.github.io
  dev_url: https://github.com/radioactivedecay/radioactivedecay


extra:
  recipe-maintainers:
    - alexmalins
